### ISSUE TITLE
[Bug] - Kotlin issue when trying to compile the app

### ISSUE THREAD

**Issue by aleluis777** [BlackBoxVision/react-native-mercadopago-px#19]
How are you I have a problem running the package. and my question is if i need to install kotlin. when running npx react-native run-android the error is the following:

> Task :blackbox-vision_react-native-mercadopago-px:compileDebugKotlin FAILED      

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
11 actionable tasks: 2 executed, 9 up-to-date

**Comment by JonatanSalas** [comment]
Would be glad you follow the Bug template as this is a required step to understand where is the point of failure: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...' 
2. Click on '...' | Scroll down to '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Dependencies**
Add the name and version of all dependencies of your project.

Please, complete the following so we had information to help you.

**Comment by JonatanSalas** [comment]
Kotlin is installed by default in the library, so that's not an issue.

**Comment by aleluis777** [comment]
**The bug:**
> Task :blackbox-vision_react-native-mercadopago-px:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings


**To Reproduce**
1.react-native init proyectmp  => _Creating a new project_
2. npm i @blackbox-vision/react-native-mercadopago-px => _Install_

•	react-native link @blackbox-vision/react-native-mercadopago-px=> _I did the result below without this step, but when I do this step I have the same error_ 


In this example, don't make any changes to the app.js and it still throws the error

3. _start android_  => npx react-native  run-android

**Expected behavior**

the app should be shown on my device

Device: [Motorola G6 Play]
OS: [ Android] : 


**Additional context**

when I run the github example the app works correctly (the example), but when I do it by installing the packages by npm I have this error.

![image](https://user-images.githubusercontent.com/24797816/89742936-0e511100-da64-11ea-9406-7590ce756e26.png)

![image](https://user-images.githubusercontent.com/24797816/89742939-19a43c80-da64-11ea-87bc-56c8a9b78a2e.png)




![image](https://user-images.githubusercontent.com/24797816/89742961-5112e900-da64-11ea-8353-1362a0c38936.png)
running the repository example, if it works properly

**Comment by JonatanSalas** [comment]
Which react-native version are you using?

**Comment by aleluis777** [comment]
"react-native": "0.63.2"
"@blackbox-vision/react-native-mercadopago-px": "^0.5.0"

**Comment by JonatanSalas** [comment]
@aleluis777 try installing `npm i @blackbox-vision/react-native-mercadopago-px@0.6.0`, it should be fixed by the following commit https://github.com/BlackBoxVision/react-native-mercadopago-px/commit/2d80a2c1e6a886b3131ee3db51dadaa0cb967478. 

Let me know if this fixes your issue!

**Comment by aleluis777** [comment]
First failure

**ERROR**: Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0 react native

**Solution:**
At Path android/app/build.gradle
defaultConfig {
multiDexEnabled true //<====Add this line
}

...and then it worked.
