### ISSUE TITLE
Valor email de Payer no puede ser cambiado

### ISSUE THREAD

**Issue by cecodor** [BlackBoxVision/react-native-mercadopago-px#24]
**Describe the bug**
Cuando se está construyendo el preference, el valor "Email" del "Payer" tiene que ser siempre "payer@email.com" si se utiliza otro, da error al momento de hacer el pago (barra roja en el footer). Lo mismo ocurre en producción y en sandbox.

**To Reproduce**
Crear un preference con un Email de Payer diferente a "payer@email.com"

**Expected behavior**
Debería poder aceptar el correo real del comprador.

**Screenshots**
![image](https://user-images.githubusercontent.com/23288172/93785711-03a5a200-fbf4-11ea-9e6a-38830d5d5454.png)

Y si es diference a ese:
![image](https://user-images.githubusercontent.com/23288172/93786247-b37b0f80-fbf4-11ea-9669-21913445dfd5.png)

**Smartphone (please complete the following information):**
 - Device: One Plus 3
 - OS: Android
 - Version: 9

**Additional context**
Igualmente, en mercadopago el pago se registra con un correo que no hace referencia al usuario que realmente lo hizo, lo que dificulta encontrar los pagos a nivel administrativo.

![image](https://user-images.githubusercontent.com/23288172/93786002-6434df00-fbf4-11ea-9d32-48abb391b42a.png)

**Comment by JonatanSalas** [comment]
@cecodor closing this issue since isn't related to the checkout itself. 

Our library only wraps the UI behind the PX SDKs, and the payment is based on the preference created server side, so it's possible an issue with the MP API or how you're consuming it. 

Go to https://www.mercadopago.com.ar/developers/es/support and reach support to see where the issue is.
