### ISSUE TITLE
Argument 0 (NSNumber) of UIManager.measure must not be null

### ISSUE THREAD

**Issue by nikpaolillo** [BlackBoxVision/react-native-mercadopago-px#28]
Hi! when my Mercado Plugin active the autofocus on input to put card number, i got this issue and i cannot continue. How i can turn off this auto Focus on Ios? i dont have any problem with Android, only Ios

Argument 0 (NSNumber) of UIManager.measure must not be null

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

![image](https://user-images.githubusercontent.com/17077141/99850018-5e5b6b80-2b5b-11eb-9f53-83368abe427c.png)

**Comment by JonatanSalas** [comment]
Would you mind to give us more information? We do have an issue template that you didn't follow, I'll mark this as a bug, but we need to understand your dependencies, your react native version, the version of our library you're using.

Until you didn't complete us that information, we aren't going to put efforts on something we can't reproduce.

**Comment by Esxiel** [comment]
There's probably somewhere in some library's code that is using UIManager.measure(firstArg, secondArg).
The firstArg is usually calculated and perhaps the function used to calculate it returned null, and that went in the measure() function, which resulted in this error.

You can change it so that if it will return null, make it return 0 instead. I'm not sure about the repercussions but it can at least stop the error.
e.g. UIManager.measure(calculateViewSomething(x) || 0, secondArg)
